//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionReservaServices.EspacioDeportivoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspacioDeportivo", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class EspacioDeportivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionReservaServices.EspacioDeportivoWS.Sede SedeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionReservaServices.EspacioDeportivoWS.Sede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EspacioDeportivoWS.IEspacioDeportivoService")]
    public interface IEspacioDeportivoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspacioDeportivoService/obtener", ReplyAction="http://tempuri.org/IEspacioDeportivoService/obtenerResponse")]
        GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo obtener(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspacioDeportivoService/lista", ReplyAction="http://tempuri.org/IEspacioDeportivoService/listaResponse")]
        GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo[] lista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspacioDeportivoService/crear", ReplyAction="http://tempuri.org/IEspacioDeportivoService/crearResponse")]
        GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo crear(string nombre, int sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspacioDeportivoService/actualizar", ReplyAction="http://tempuri.org/IEspacioDeportivoService/actualizarResponse")]
        GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo actualizar(int codigo, string nombre, int sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEspacioDeportivoService/eliminar", ReplyAction="http://tempuri.org/IEspacioDeportivoService/eliminarResponse")]
        void eliminar(int Codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEspacioDeportivoServiceChannel : GestionReservaServices.EspacioDeportivoWS.IEspacioDeportivoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EspacioDeportivoServiceClient : System.ServiceModel.ClientBase<GestionReservaServices.EspacioDeportivoWS.IEspacioDeportivoService>, GestionReservaServices.EspacioDeportivoWS.IEspacioDeportivoService {
        
        public EspacioDeportivoServiceClient() {
        }
        
        public EspacioDeportivoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EspacioDeportivoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EspacioDeportivoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EspacioDeportivoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo obtener(int Codigo) {
            return base.Channel.obtener(Codigo);
        }
        
        public GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo[] lista() {
            return base.Channel.lista();
        }
        
        public GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo crear(string nombre, int sede) {
            return base.Channel.crear(nombre, sede);
        }
        
        public GestionReservaServices.EspacioDeportivoWS.EspacioDeportivo actualizar(int codigo, string nombre, int sede) {
            return base.Channel.actualizar(codigo, nombre, sede);
        }
        
        public void eliminar(int Codigo) {
            base.Channel.eliminar(Codigo);
        }
    }
}
