//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionReservaAppMVC.GestionReservaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspacioDeportivo", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class EspacioDeportivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionReservaAppMVC.GestionReservaWS.Sede SedeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionReservaAppMVC.GestionReservaWS.Sede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
    [System.SerializableAttribute()]
    public partial class ValidationException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationError {
            get {
                return this.ValidationErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationErrorField, value) != true)) {
                    this.ValidationErrorField = value;
                    this.RaisePropertyChanged("ValidationError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Horario", Namespace="http://schemas.datacontract.org/2004/07/GestionReservaServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Horario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dia {
            get {
                return this.DiaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaField, value) != true)) {
                    this.DiaField = value;
                    this.RaisePropertyChanged("Dia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reserva", Namespace="http://schemas.datacontract.org/2004/07/GestionReservaServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadHorasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoEspacioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaInicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadHoras {
            get {
                return this.CantidadHorasField;
            }
            set {
                if ((this.CantidadHorasField.Equals(value) != true)) {
                    this.CantidadHorasField = value;
                    this.RaisePropertyChanged("CantidadHoras");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoEspacio {
            get {
                return this.CodigoEspacioField;
            }
            set {
                if ((this.CodigoEspacioField.Equals(value) != true)) {
                    this.CodigoEspacioField = value;
                    this.RaisePropertyChanged("CodigoEspacio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dia {
            get {
                return this.DiaField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaField, value) != true)) {
                    this.DiaField = value;
                    this.RaisePropertyChanged("Dia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaFinField, value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaInicioField, value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionReservaWS.IGestionReservaService")]
    public interface IGestionReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/obtenerEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/obtenerEspacioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/obtenerEspacioValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo obtenerEspacio(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/listarEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/listarEspacioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/listarEspacioValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo[] listarEspacio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/crearEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/crearEspacioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/crearEspacioValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string crearEspacio(string nombre, int sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/actualizarEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/actualizarEspacioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/actualizarEspacioValidationExceptionFau" +
            "lt", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string actualizarEspacio(int codigo, string nombre, int sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/eliminarEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/eliminarEspacioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/eliminarEspacioValidationExceptionFault" +
            "", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string eliminarEspacio(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/listarSede", ReplyAction="http://tempuri.org/IGestionReservaService/listarSedeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/listarSedeValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        GestionReservaAppMVC.GestionReservaWS.Sede[] listarSede();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/registrarHorario", ReplyAction="http://tempuri.org/IGestionReservaService/registrarHorarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/registrarHorarioValidationExceptionFaul" +
            "t", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string registrarHorario(int codigo, string dia, string horaInicio, string horaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/actualizarHorario", ReplyAction="http://tempuri.org/IGestionReservaService/actualizarHorarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/actualizarHorarioValidationExceptionFau" +
            "lt", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string actualizarHorario(int codigo, string dia, string horaInicio, string horaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/obtenerHorario", ReplyAction="http://tempuri.org/IGestionReservaService/obtenerHorarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/obtenerHorarioValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        GestionReservaAppMVC.GestionReservaWS.Horario obtenerHorario(int codigo, string dia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/eliminarHorario", ReplyAction="http://tempuri.org/IGestionReservaService/eliminarHorarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/eliminarHorarioValidationExceptionFault" +
            "", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string eliminarHorario(int codigo, string dia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/listarHorario", ReplyAction="http://tempuri.org/IGestionReservaService/listarHorarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/listarHorarioValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        GestionReservaAppMVC.GestionReservaWS.Horario[] listarHorario(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/registrarReserva", ReplyAction="http://tempuri.org/IGestionReservaService/registrarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/registrarReservaValidationExceptionFaul" +
            "t", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string registrarReserva(int codigoEspacio, int cantHoras, string fechaInicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/confirmarReserva", ReplyAction="http://tempuri.org/IGestionReservaService/confirmarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/confirmarReservaValidationExceptionFaul" +
            "t", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string confirmarReserva(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/cancelarReserva", ReplyAction="http://tempuri.org/IGestionReservaService/cancelarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/cancelarReservaValidationExceptionFault" +
            "", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        string cancelarReserva(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/obtenerReserva", ReplyAction="http://tempuri.org/IGestionReservaService/obtenerReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/obtenerReservaValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        GestionReservaAppMVC.GestionReservaWS.Reserva obtenerReserva(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/listarReserva", ReplyAction="http://tempuri.org/IGestionReservaService/listarReservaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GestionReservaAppMVC.GestionReservaWS.ValidationException), Action="http://tempuri.org/IGestionReservaService/listarReservaValidationExceptionFault", Name="ValidationException", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Excepcion")]
        GestionReservaAppMVC.GestionReservaWS.Reserva[] listarReserva();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionReservaServiceChannel : GestionReservaAppMVC.GestionReservaWS.IGestionReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionReservaServiceClient : System.ServiceModel.ClientBase<GestionReservaAppMVC.GestionReservaWS.IGestionReservaService>, GestionReservaAppMVC.GestionReservaWS.IGestionReservaService {
        
        public GestionReservaServiceClient() {
        }
        
        public GestionReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo obtenerEspacio(int codigo) {
            return base.Channel.obtenerEspacio(codigo);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo[] listarEspacio() {
            return base.Channel.listarEspacio();
        }
        
        public string crearEspacio(string nombre, int sede) {
            return base.Channel.crearEspacio(nombre, sede);
        }
        
        public string actualizarEspacio(int codigo, string nombre, int sede) {
            return base.Channel.actualizarEspacio(codigo, nombre, sede);
        }
        
        public string eliminarEspacio(int Codigo) {
            return base.Channel.eliminarEspacio(Codigo);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.Sede[] listarSede() {
            return base.Channel.listarSede();
        }
        
        public string registrarHorario(int codigo, string dia, string horaInicio, string horaFin) {
            return base.Channel.registrarHorario(codigo, dia, horaInicio, horaFin);
        }
        
        public string actualizarHorario(int codigo, string dia, string horaInicio, string horaFin) {
            return base.Channel.actualizarHorario(codigo, dia, horaInicio, horaFin);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.Horario obtenerHorario(int codigo, string dia) {
            return base.Channel.obtenerHorario(codigo, dia);
        }
        
        public string eliminarHorario(int codigo, string dia) {
            return base.Channel.eliminarHorario(codigo, dia);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.Horario[] listarHorario(int codigo) {
            return base.Channel.listarHorario(codigo);
        }
        
        public string registrarReserva(int codigoEspacio, int cantHoras, string fechaInicio) {
            return base.Channel.registrarReserva(codigoEspacio, cantHoras, fechaInicio);
        }
        
        public string confirmarReserva(int codigo) {
            return base.Channel.confirmarReserva(codigo);
        }
        
        public string cancelarReserva(int codigo) {
            return base.Channel.cancelarReserva(codigo);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.Reserva obtenerReserva(int codigo) {
            return base.Channel.obtenerReserva(codigo);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.Reserva[] listarReserva() {
            return base.Channel.listarReserva();
        }
    }
}
