//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1008
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionReservaAppMVC.GestionReservaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspacioDeportivo", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class EspacioDeportivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestionReservaAppMVC.GestionReservaWS.Sede SedeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestionReservaAppMVC.GestionReservaWS.Sede Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sede", Namespace="http://schemas.datacontract.org/2004/07/EspacioDeportivoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Sede : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GestionReservaWS.IGestionReservaService")]
    public interface IGestionReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/obtenerEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/obtenerEspacioResponse")]
        GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo obtenerEspacio(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/listarEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/listarEspacioResponse")]
        GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo[] listarEspacio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/crearEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/crearEspacioResponse")]
        GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo crearEspacio(string nombre, int sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/actualizarEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/actualizarEspacioResponse")]
        GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo actualizarEspacio(int codigo, string nombre, int sede);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/eliminarEspacio", ReplyAction="http://tempuri.org/IGestionReservaService/eliminarEspacioResponse")]
        void eliminarEspacio(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionReservaService/listarSede", ReplyAction="http://tempuri.org/IGestionReservaService/listarSedeResponse")]
        GestionReservaAppMVC.GestionReservaWS.Sede[] listarSede();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionReservaServiceChannel : GestionReservaAppMVC.GestionReservaWS.IGestionReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionReservaServiceClient : System.ServiceModel.ClientBase<GestionReservaAppMVC.GestionReservaWS.IGestionReservaService>, GestionReservaAppMVC.GestionReservaWS.IGestionReservaService {
        
        public GestionReservaServiceClient() {
        }
        
        public GestionReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo obtenerEspacio(int codigo) {
            return base.Channel.obtenerEspacio(codigo);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo[] listarEspacio() {
            return base.Channel.listarEspacio();
        }
        
        public GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo crearEspacio(string nombre, int sede) {
            return base.Channel.crearEspacio(nombre, sede);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.EspacioDeportivo actualizarEspacio(int codigo, string nombre, int sede) {
            return base.Channel.actualizarEspacio(codigo, nombre, sede);
        }
        
        public void eliminarEspacio(int Codigo) {
            base.Channel.eliminarEspacio(Codigo);
        }
        
        public GestionReservaAppMVC.GestionReservaWS.Sede[] listarSede() {
            return base.Channel.listarSede();
        }
    }
}
